### ISSUE TITLE
add compile instructions?

### ISSUE THREAD

**Issue by yzhh029** [xuanyi-fu/xynet#2]
Can you add compile instructions? Thank you

**Comment by xuanyi-fu** [comment]
Sure. I am planning to add the README and compile instructions after I finishing tests in /test.

For now, you can try to compile this with:

Linux kernel: > 5.6

Compiler: gcc10.1 or gcc10.0.1 with libstdc++

Dependencies: 
OpenSSL for SHA-1 in WebSockets. (It should be removed later by implementing SHA-1 directly)
Liburing-0.6 for io_uring utilities https://github.com/axboe/liburing
doctest for tests https://github.com/onqtam/doctest
g3logger for logging https://github.com/KjellKod/g3log (This is for debugging the coroutine stack and will be removed later. GCC now has many subtle bugs when using the cppcoro with it )

clang10 with libc++ is not supported because clang still uses the  `<experimental/coroutine>` instead of `<coroutine>` and also lacks the `<ranges>`, which is essential to xynet/buffer_seqneuce.h.

If you have any trouble in compiling it, please let me know!
